apiVersion: v2
name: jellyfin
description: Jellyfin is the volunteer-built media solution that puts you in control of your media.
icon: https://avatars.githubusercontent.com/u/45698031?s=48&v=4
type: application
version: 0.0.3
appVersion: 10.9.11
home: https://jellyfin.org/
sources:
  - https://github.com/jellyfin/jellyfin
annotations:
  displayName: Jellyfin
