apiVersion: v2
name: postgres
description: PostgreSQL is a powerful, open source object-relational database (with pgvecto.rs installed).
icon: https://avatars.githubusercontent.com/u/177543?s=48&v=4
type: application
version: 0.0.9
appVersion: pg15-v0.2.0
home: https://www.postgresql.org/
sources:
  - https://github.com/postgres/postgres
annotations:
  displayName: PostgreSQL
